<?
$PERM["personal"]["24"]="W";
$PERM["catalog"]["24"]="W";
$PERM["news"]["24"]="W";
$PERM["news"]["5"]="W";
$PERM["about"]["24"]="W";
$PERM["index.php"]["24"]="W";
$PERM["index.php"]["5"]="W";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["upload"]["23"]="T_8";
$PERM["cataloge"]["7"]="W";
$PERM["util"]["2"]="D";
$PERM["articles"]["5"]="W";
$PERM["projects"]["5"]="W";
$PERM["reviews"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["/"]["*"]="R";
?>