<?$APPLICATION->IncludeComponent("bitrix:search.title", "catalog", array(
	"CATEGORY_0" => array(
			0 => "iblock_catalog",
		),
		"CATEGORY_0_TITLE" => GetMessage("CATEGORY_PRODUСTCS_SEARCH_NAME"),
		"CATEGORY_0_iblock_aspro_optimus_catalog" => array(
			0 => "185",
		),
		"CATEGORY_0_iblock_catalog" => array(
			0 => "114",
			1 => "115",
			2 => "116",
			3 => "117",
			4 => "118",
			5 => "119",
			6 => "120",
			7 => "123",
			8 => "132",
			9 => "171",
		),
		"CHECK_DATES" => "Y",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"CONTAINER_ID" => "title-search",
		"CONVERT_CURRENCY" => "N",
		"INPUT_ID" => "title-searchs-input",
		"NUM_CATEGORIES" => "1",
		"ORDER" => "date",
		"PAGE" => SITE_DIR."catalog/search/",
		"PREVIEW_HEIGHT" => "38",
		"PREVIEW_TRUNCATE_LEN" => "50",
		"PREVIEW_WIDTH" => "38",
		"PRICE_CODE" => array(
			0 => "Д  5%",
			1 => "Цена ИМ(СпецЦена2)",
			2 => "Исходная розничная",
			3 => "Ручная_2",
			4 => "Розничная (Дилерская 10%)",
			5 => "СпЦ 1 - 1%",
			6 => "СпЦ 2",
			7 => "Д 12%",
			8 => "СпЦ 1",
			9 => "Розн.",
			10 => "Д 10%",
		),
		"PRICE_VAT_INCLUDE" => "Y",
		"SHOW_ANOUNCE" => "N",
		"SHOW_INPUT" => "Y",
		"SHOW_OTHERS" => "N",
		"SHOW_PREVIEW" => "Y",
		"TOP_COUNT" => "5",
		"USE_LANGUAGE_GUESS" => "Y",
		"COMPONENT_TEMPLATE" => "catalog"
	),
	false,
	array(
	"ACTIVE_COMPONENT" => "Y"
	)
);?>