<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("План семинара по ИСО Орион");
?> 
<p class="MsoNormal" style="margin-left: 42.55pt; text-align: justify;"><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;"> 
    <br />
   </span></p>

<p class="MsoNormal" style="text-align: center; margin-left: 42.55pt;"><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;"><b>План семинара по ИСО &laquo;Орион&raquo;.</b></span></p>
 
<p class="MsoNormal" style="margin-left: 42.55pt; text-align: justify;"><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">1.  Архитектура системы. Магистральный интерфейс RS-485, физическая структура и протокол передачи данных; параметры интерфейса, разновидности архитектур, повторители и преобразователи для ближней связи. Трансляция магистрального интерфейса RS-485 на дальние дистанции, преобразователи «С2000-</span><span lang="EN-US" style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">USB</span><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">», «</span><span lang="EN-US" style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">USB</span><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">-</span><span lang="EN-US" style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">RS</span><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">485», «</span><span lang="EN-US" style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">USB</span><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">-</span><span lang="EN-US" style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">RS</span><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">232», «</span><span lang="EN-US" style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">C</span><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">2000-</span><span lang="EN-US" style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">Ethernet</span><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">», «С2000-РПИ». Преобразователь протокола системы «Орион» в </span><span lang="EN-US" style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">Modbus-RTU </span><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">«С2000-ПП».</span></p>
 
<p class="MsoNormal" style="margin-left: 42.55pt; text-align: justify;"><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">2.  ТТХ и работа приборов; инновационный ППКОП «Сигнал-10», адресные пороговые извещатели «ДИП-34ПА», «С2000-ИППА», «ИПР-513-3ПАМ». Приемно-контрольные приборы (&quot;Сигнал-20 исп.02&quot;, &quot;Сигнал-20П&quot;, &quot;Сигнал-20М&quot;, &quot;</span><span lang="EN-US" style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">C</span><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">2000-4&quot;) извещатели и приборы управления; вспомогательное оборудование. Радиоканальный расширитель системы ОПС «С2000-</span><span lang="EN-US" style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">Adem</span><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">». Автономный дымовой пожарный извещатель «ДИП-34АВТ». </span><span lang="EN-US" style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">Новый контроллер периметральных извещателей &ldquo;С2000-Периметр&rdquo;.</span></p>
 
<p class="MsoNormal" style="margin-left: 42.55pt; text-align: justify;"><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">3.  Адресная двухпроводная подсистемы передачи извещений &quot;СПИ-2000А&quot;. Новое семейство контроллеров «С2000-КДЛ-2И». </span><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">Пожарные адресно-аналоговые автоматические извещатели и адресный ручной «ИПР-513-3АМ» в новом исполнении. Элемент дистанционного управления ЭДУ 513-3АМ. Монтажные комплекты для адресно-аналоговых извещателей. Способы и конфликты адресации. Новый адресный релейный блок «С2000-СП2 исп.02», адресный релейный блок для управления приводами клапанов дымоудаления и вентиляции «С2000-СП4». Охранные адресные извещатели; расширители: АР-1, включаемые через него типы ШС, АР-2, АР-8. Блок расширения шлейфов сигнализации взрывозащищенный «С2000-БРШС-Ех». Адресные <a href="http://local.bolid.ru/production/devices/devices_172.html" ><span style="color: windowtext; text-decoration: none;">термогигрометр</span></a>ы «С2000-ВТ». Отказоустойчивость ДПЛС, модули БРИЗ, БРИЗ-01; ответвления и структура линии</span><span style="line-height: 1.4;">.</span></p>
 
<p class="MsoNormal" style="margin-left: 42.55pt; text-align: justify;"><span style="font-size: 10pt; line-height: 18.200000762939453px;">4.  </span><span style="font-family: 'Microsoft Sans Serif', sans-serif; font-size: 10pt; line-height: 1.4;">Управление пожаротушением. Приборы пожарные управления &quot;С2000-АСПТ&quot; вер.3.0х. Газовые и порошковые модули, особенности контроля состояния. Контрольно-пусковой блок &quot;С2000-КПБ&quot; 2.0х и </span><span style="font-family: 'Microsoft Sans Serif', sans-serif; font-size: 10pt; line-height: 1.4;">блок индикации и управления пожаротушением</span><span style="font-family: 'Microsoft Sans Serif', sans-serif; font-size: 10pt; line-height: 1.4; color: rgb(83, 128, 154);"> </span><span style="font-family: 'Microsoft Sans Serif', sans-serif; font-size: 10pt; line-height: 1.4;">&quot;С2000-ПТ&quot;. Особенности водяного спринклерного тушения. Новая версия прибора &quot;Поток-3Н&quot; 1.05. Новый блок индикации и управления водяным пожаротушением «Поток-БКИ». Шкафы контрольно-пусковые ШКП, шкаф «ШКП 250» с возможностью организации «плавного пуска». </span><span class="ttl1" style="font-family: 'Microsoft Sans Serif', sans-serif; font-size: 10pt; line-height: 1.4;"><span style="color: windowtext;">Приборы речевого оповещения &quot;Рупор&quot; и «Рупор исп. 01». Прибор речевого оповещения «Рупор-200». Комплекс технических средств «Рупор &ndash; Диспетчер».</span></span></p>
 
<p class="MsoNormal" style="margin-left: 42.55pt; text-align: justify;"><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">5.  Две линейки резервированных источников питания «РИП» (для <a href="http://local.bolid.ru/production/reserve/reserve_218.html" ><span style="color: windowtext; text-decoration: none;">технических средств пожарной автоматики (сертифицированы по ГОСТ Р 53325-2009)</span></a> и общего применения с микропроцессорным управлением). Дополнительные периферийные модули: модуль преобразования напряжений, модуль контроля состояния, модуль контроля резервного питания, блок защитный сетевой, блок защитный коммутационный. Источники питания  с информационным </span><span lang="EN-US" style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">RS</span><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">-485 интерфейсом. Блоки питания «РИП 12 исп.06», «РИП-24 исп.06» с повышенной емкостью аккумуляторов. Новые названия линейки источников питания.</span></p>
 
<p class="MsoNormal" style="margin-left: 42.55pt; text-align: justify;"><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">6.  Контроллеры доступа ИСО «Орион». Прибор приемно-контрольный с функциями контроля доступа «С2000-4» 3.0х. Новое поколение контроллеров «С2000-2» вер.2.0х. Перспективный сетевой контроллер «С2000-КД». Считыватели производства НВП «Болид». Применение настольных считывателей с </span><span lang="EN-US" style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">USB</span><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;"> интерфейсом. Биометрические контроллеры «С2000-</span><span lang="EN-US" style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">BIOAccess</span><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">».</span></p>
 
<p class="MsoNormal" style="margin-left: 42.55pt; text-align: justify;"><span style="font-family: 'Microsoft Sans Serif', sans-serif; font-size: 10pt; line-height: 1.4;">7.  Центральные контроллеры ИСО &quot;Орион&quot;. Пульты &quot;С2000&quot;, &quot;С2000-КС&quot;. Перспективная версия пульта «С2000М» 2.07 с расширенными функциями управления дымоудалением. Резервирование функций управления, возможности и ограничения. Режимы работы. Утилита Pprog: конфигурирование и управление системой. Основные понятия системы: шлейфы, зоны, разделы. Тактики управления постановкой/снятием с охраны ШС и разделов системы (локальное, централизованное, автоматическое управление). Общий обзор, упоминание малых конфигураций и различных версий, сравнение функциональности АРМ &quot;Орион Про&quot; и пульта в роли ЦКС. Блок индикации и управления ОПС и клапанами «С2000-БКИ». Новый блок индикации «С2000-БИ исп.02». Перспективный пульт «С3000».</span></p>
 
<p class="MsoNormal" style="margin-left: 42.55pt; text-align: justify;"><span style="font-family: 'Microsoft Sans Serif', sans-serif; font-size: 10pt; line-height: 1.4;">8.  АРМ &quot;Орион&quot;: основные понятия, устройство, конфигурирование; состав: администратор базы данных, мастер системы, оперативная задача. Сетевой клиент «Учет рабочего времени».</span></p>
 
<p class="MsoNormal" style="margin-left: 42.55pt; text-align: justify;"><span style="font-family: 'Microsoft Sans Serif', sans-serif; font-size: 10pt; line-height: 1.4;">9.  АРМ «Орион ПРО». Краткий обзор системы. Основные характеристики системы. Сетевые модули системы. Архитектура системы. Протокол «Орион ПРО». Принципы управления в системе, терминология. Краткое сравнение с АРМ «Орион».</span></p>
 
<p class="MsoNormal" style="margin-left: 42.55pt; text-align: justify;"><span style="font-family: 'Microsoft Sans Serif', sans-serif; font-size: 10pt; line-height: 1.4;">10. Построение систем видеонаблюдения на сетевых камерах на базе &quot;Орион Видео Про&quot;. Сетевые камеры. Принципы и особенности применения. Преимущества сетевых камер. Применение &quot;Орион Видео Про&quot;.</span></p>
 
<p class="MsoNormal" style="margin-left: 42.55pt; text-align: justify;"><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">11. Системы передачи извещений и мониторинга. Устройства передачи извещений «С2000-ИТ», «УО-4С исп.02». Перспективное оконечное устройство «</span><span lang="EN-US" style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">C</span><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">2000-</span><span lang="EN-US" style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">PGE</span><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">». Новая РСПИ «Орион Радио». АРМ «Эгида исп. 03».</span></p>
 
<p class="MsoNormal" style="margin-left: 42.55pt; text-align: justify;"><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">12. Адресные счётчики расхода/количества «</span><span lang="EN-US" style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">C</span><span style="font-size: 10pt; font-family: 'Microsoft Sans Serif', sans-serif;">2000-АСР2», АРМ «Ресурс». Перспективные счетчики расхода «С2000-АСР2 исп.01» и «С2000-АСР8».</span></p>
 
<p class="MsoNormal" style="margin-left: 42.55pt; text-align: justify;"><span style="font-family: 'Microsoft Sans Serif', sans-serif; font-size: 10pt; line-height: 1.4;">13. Системы управления инженерными системами и жизнеобеспечением здания, построенные на оборудовании ИСО «Орион». </span><span style="font-family: 'Microsoft Sans Serif', sans-serif; font-size: 10pt; line-height: 1.4; color: windowtext; text-decoration: none;">Контроллеры технологические</span><span style="font-family: 'Microsoft Sans Serif', sans-serif; font-size: 10pt; line-height: 1.4;"> «С2000-Т», «С2000-Т» исп.01. SCADA «Алгоритм».</span></p>
 
<p class="MsoNormal" style="margin-left: 42.55pt; text-align: justify;"><span style="font-family: 'Microsoft Sans Serif', sans-serif; font-size: 10pt; line-height: 1.4;">14. Системы </span><span style="font-family: 'Microsoft Sans Serif', sans-serif; font-size: 10pt; line-height: 1.4; color: windowtext; text-decoration: none;">для определения и регистрации маршрутов следования автотранспортных средств</span><span style="font-family: 'Microsoft Sans Serif', sans-serif; font-size: 10pt; line-height: 1.4;"> «Орма 2» и «Орма 3». </span></p>
 <?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>